name: Unit Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run unit tests
        shell: bash
        run: |
          poetry run pytest --cov=src src/

      - name: Process coverage files
        env:
          COVERAGE_RCFILE: "pyproject.toml"
        run: |
          poetry run coverage report --debug=sys,config,callers
          poetry run coverage xml --debug=sys,config,callers
          poetry run diff-cover coverage.xml --html-report coverage.html --config-file pyproject.toml

      - name: GitHub Coverage
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdNew: 1
          thresholdModified: 0.90
          thresholdAll: 0.95

      - name: Upload code coverage reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          retention-days: 1
          path: |
            coverage.xml
            coverage.html
            .coverage
